### ISSUE TITLE
Expand Behat tests to test more adapters

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#279]
The Behat test suite should be configurable so that all the different database / storage adapters could be tested. This might be possible to achieve with the usage of profiles.

**Comment by cybernet** [comment]
any news ?

**Comment by rexxars** [comment]
Unfortunately, no. Once Imbo 2.0 is out the door, we'll be looking to upgrade behat to the latest version, which might make this easier. Placing this up for grabs if anyone wants to take a shot.

**Comment by christeredvartsen** [comment]
This will most likely be implemented in #404, closing for now.

**Comment by christeredvartsen** [comment]
Re-opening as this hasn't yet been achieved.

**Comment by christeredvartsen** [comment]
I've finally started working on this task. For now the most logical choice is to create different suites in `behat.yml.dist` for combinations of a database and storage adapter. Each suite can have its own feature context class that extends an abstract feature context class, where the different steps are located. This allows for each suite to have different setup / teardown methods.

So, by using suites:

```yaml
default:
    autoload:
        '': %paths.base%/tests/behat/features/bootstrap
    suites:
        mongodb-gridfs:
            paths: [%paths.base%/tests/behat/features]
            contexts: [MongoDBGridFSContext]
        doctrine-filesystem:
            paths: [%paths.base%/tests/behat/features]
            contexts: [DoctrineFilesystemContext]
        doctrine-s3:
            paths: [%paths.base%/tests/behat/features]
            contexts: [DoctrineS3Context]

    extensions:
        Imbo\BehatApiExtension:
            apiClient:
                base_uri: http://localhost:8080
```
